# Generated by Django 4.2.14 on 2025-09-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='feedback',
            field=models.JSONField(default=list, help_text='Feedback for each letter: correct, wrong_position, incorrect'),
        ),
    ]
